# Generated by Django 4.2.4 on 2023-08-11 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_person_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfCorrectAnswers', models.IntegerField(default=0)),
                ('firstname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_firstname', to=settings.AUTH_USER_MODEL)),
                ('surname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_surname', to=settings.AUTH_USER_MODEL)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
