# Generated by Django 4.2.4 on 2023-08-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_student_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='noOfCorrectAnswers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
