# Generated by Django 4.2.4 on 2023-08-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
