# Generated by Django 4.2.4 on 2023-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='totalQuestionsAnswered',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
