# Generated by Django 4.2.4 on 2023-08-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_class_student_classname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dueDate', models.DateField(null=True)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.class')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionInAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.assignment')),
                ('questionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
            ],
        ),
    ]
