# Generated by Django 4.2.4 on 2023-08-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_questioninassignment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentAnswer', models.CharField(max_length=200, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('assignmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.assignment')),
                ('questionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
            options={
                'unique_together': {('studentID', 'questionID', 'assignmentID')},
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('assignmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.assignment')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
            options={
                'unique_together': {('studentID', 'assignmentID')},
            },
        ),
    ]
