# Generated by Django 4.2.4 on 2023-08-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_studentquestionassignment_studentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='noCorrectAnswers',
            field=models.IntegerField(default=0),
        ),
    ]
