# Generated by Django 4.2.4 on 2023-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_studentassignment_nocorrectanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionassignment',
            name='studentanswer2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
