# Generated by Django 4.2.4 on 2023-08-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_studentquestionassignment_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquestionassignment',
            old_name='studentanswer2',
            new_name='studentanswer3',
        ),
    ]
