# Generated by Django 4.2.4 on 2023-08-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_rename_studentanswer_studentquestionassignment_studentanswer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquestionassignment',
            name='studentanswer3',
        ),
    ]
