# Generated by Django 4.2.4 on 2023-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_studentquestionassignment_studentanswer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestionassignment',
            name='realStudentAnswer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
