# Generated by Django 4.2.4 on 2023-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_studentquestionassignment_realstudentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
