# Generated by Django 4.2.4 on 2023-08-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_studentassignment_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.questioncategory'),
        ),
    ]
