# Generated by Django 4.2.4 on 2023-08-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_question_questiontopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionTopic',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.class'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.questioncategory'),
        ),
    ]
