# Generated by Django 4.2.4 on 2023-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_question_questiontopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizCorrectAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='quizQuestionsAnswered',
            field=models.IntegerField(default=0),
        ),
    ]
