# Generated by Django 4.2.4 on 2023-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_student_quizcorrectanswers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quizAverage',
            field=models.FloatField(default=0),
        ),
    ]
