# Generated by Django 4.2.4 on 2023-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_student_quizaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='noOfQuizzesCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
