# Generated by Django 4.2.4 on 2023-09-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_targetgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='TargetGrade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.targetgrade'),
        ),
    ]
