# Generated by Django 4.2.4 on 2023-09-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_student_targetgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='TargetGrade',
            new_name='targetGrade',
        ),
    ]
