# Generated by Django 4.2.4 on 2023-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_rename_targetgrade_student_targetgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgrade',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
