# Generated by Django 4.2.4 on 2023-09-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_targetgrade_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetGrade',
            new_name='Grade',
        ),
    ]
