# Generated by Django 4.2.4 on 2023-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_rename_targetgrade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='isQuiz',
            field=models.BooleanField(default=False),
        ),
    ]
