# Generated by Django 4.2.4 on 2023-09-05 15:22

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_studentassignment_isquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='targetGrade',
            field=models.ForeignKey(default=app1.models.getDefaultGrade, on_delete=django.db.models.deletion.CASCADE, to='app1.grade'),
        ),
    ]
