# Generated by Django 4.2.4 on 2023-09-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_student_targetgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
