# Generated by Django 4.2.4 on 2023-10-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_questioncategory_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('average', models.IntegerField(default=0)),
                ('categoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.questioncategory')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
