# Generated by Django 4.2.4 on 2023-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_class_options_alter_questioncategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='studentcategory',
            unique_together={('studentID', 'categoryID')},
        ),
    ]
