# Generated by Django 4.2.4 on 2023-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_alter_studentcategory_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='dateCompleted',
            field=models.DateField(default=None, null = True),
        ),
    ]
