# Generated by Django 4.2.4 on 2023-10-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_studentassignment_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='dateCompleted',
            field=models.DateField(default=None, null=True),
        ),
    ]
